Add: signUp,login API 구현
wecode-bootcamp-korea/10-Likey-backend pull request #2
Opened 2020-08-04 13:25 UTC by dhgh95

## 수정 사항 간략한 한줄 요약
- 로그인 회원가입 API 구현
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-08-05 12:40 UTC, joonseokhu requested changes

2020-08-05 12:40 UTC, joonseokhu commented on controllers/auth.js
> +      "supersecrettoken",
토큰 사이닝에 쓰이는 키는 보안상 위험 때문에 환경변수로 만들어서 사용해야 합니다.

2020-08-05 12:40 UTC, joonseokhu commented on controllers/auth.js
> +    const userData = new User({
User 클래스가 현재 파일에 없는것 같습니다

2020-08-05 18:05 UTC, joonseokhu commented on middleware/is_auth.js
> +  req.userEmail = decodedToken.email;
현재 요청의 유저를 구분할때 email 말고 id로 구분하는게 좋습니다

2020-08-05 18:06 UTC, joonseokhu commented on middleware/is_auth.js
> +    decodedToken = jwt.verify(token, "supersecrettoken");
토큰 사이닝 키는 코드에 넣지말고 환경변수로 분리하세요

2020-08-05 18:07 UTC, joonseokhu commented on middleware/is_auth.js
> +  req.userEmail = decodedToken.email;
await 를 쓰기 위해 변수 네임스페이스를 만들고 try/catch 하는대신 그냥 then/catch 메서드 쓰는게 더 깔끔할 수도 있습니다.

2020-08-05 18:08 UTC, joonseokhu commented on services/auth.js
> +}
파라미터 이름이 헷갈립니다.

2020-08-10 06:57 UTC, dhgh95 commented
feature/refactor 반영했습니다

2020-08-10 06:57 UTC, closed without merging