[Likey: 최 준] Add: scraper 구현
wecode-bootcamp-korea/10-Likey-backend pull request #3
Opened 2020-08-04 14:10 UTC by Jun4928

## 수정 사항 간략한 한줄 요약
- puppeteer library를 사용한 데이터 scraper 구현
		 
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-08-05 18:31 UTC, joonseokhu requested changes

2020-08-05 18:31 UTC, joonseokhu commented on scraper/getColors.js
> +};
퍼페티어에서 에러가 발생할 경우, 퍼페티어에 의한 브라우저를 잘 종료해줄 필요가 있습니다.
try/catch/finally 문을 써서, 함수내 모든 비동기 로직이 성공적으로 완료되거나 / 도중 에러가 발생하거나 상관없이 항상 브라우저를 닫을수 있도록 해보세요

2020-08-05 18:31 UTC, joonseokhu commented on scraper/getProductObject.js
> +      ...document.querySelectorAll("#product-option_color a.input-radio"),
nodejs 에선 document 객체가 없습니다. 다른식으로 해주세요

2020-08-05 18:31 UTC, joonseokhu commented on scraper/getProductObject.js
> +      : false;
boolean 값을 얻기위해 삼항연산자를 쓰는건 무의미합니다.

```js
const isForMember = !!document.querySelector(".member-access-msg")
```

이렇게 쓰세요

2020-08-05 18:31 UTC, joonseokhu commented on scraper/getProductObject.js
> +  const urls = require("./links.json");
require 문은 각 파일의 제일 바깥 스코프에서 실행되어야 합니다. 이래도 작동은 하겠지만 안티패턴입니다.

2020-08-05 18:31 UTC, joonseokhu commented on scraper/getProductObject.js
> +  }
for-of 문은 비동기 코드를 **순차적으로** 실행합니다. 성능적으로 문제가 생길수 있으니 병렬적으로 실행하도록 바꿔주세요.

2020-08-05 18:31 UTC, joonseokhu commented on scraper/getProductObject.js
> +main();
크롤러는 노드 실행되기 시작하는 한번만 작동해선 안됩니다. 함수로 내보내주시고, 함수의 실행은 크론잡이나 api 호출에 의해 이루어지도록 해주세요

2020-08-05 18:31 UTC, joonseokhu commented on scraper/getProductsUrls.js
> +  );
여기도 파일 생성 함수가 promise에 의해 제어되도록 바꾸어주세요

2020-08-05 18:31 UTC, joonseokhu commented on scraper/getProductsUrls.js
> +  }
여기도 비동기코드가 병렬실행되도록 바꾸어주세요

2020-08-06 05:11 UTC, Jun4928 commented on scraper/getProductObject.js
> +  const urls = require("./links.json");
넵. 수정했습니다!

2020-08-06 05:11 UTC, Jun4928 commented on scraper/getProductObject.js
> +      : false;
와.. 활용할 곳이 많겠네요..!! 감사합니다!

2020-08-06 05:13 UTC, Jun4928 commented on scraper/getProductObject.js
> +      ...document.querySelectorAll("#product-option_color a.input-radio"),
puppeteer 라이브러리의 page.evaluate 함수의 인자로 들어가는 callback 함수는 브라우저로 띄운 페이지의 맥락에서 실행되기 때문에 document 객체를 참조해서 값들을 가져올 수 있었습니다!

2020-08-06 05:13 UTC, Jun4928 commented on scraper/getColors.js
> +};
넵!!

2020-08-06 05:15 UTC, Jun4928 commented on scraper/getProductObject.js
> +  }
크롤링을 시도한 나이키 사이트가 매크로가 꺼져있어서, puppeteer 브라우저를 링크마다 새롭게 띄어주어야 했습니다. 모든 링크를 한 번에 병렬처리 하기에 메모리 누수 현상이 발생해서, chunk 로 나눈다음에 promise.all 로 병렬처리를 시도 해 봤습니다.

2020-08-06 05:16 UTC, Jun4928 commented on scraper/getProductObject.js
> +main();
현재 scraper 안에 작성한 함수들은 초기에 한 번 크롤링을 시도하는 코드입니다. (초기 크롤링 후 DB에 상품정보를 넣었습니다.) 매 번 실행시킬 일이 없기 때문에 이렇게 작성 해 봤습니다.

2020-08-06 05:17 UTC, Jun4928 commented on scraper/getProductsUrls.js
> +  }
수정했습니다. 리뷰 감사합니다!

2020-08-06 06:13 UTC, Jun4928 commented on scraper/getProductsUrls.js
> +  );
네 수정했습니다!

2020-08-06 16:02 UTC, merged