[Likey: 최 준, 오호근] Add: 장바구니 API 구현 및 테스트 완료
wecode-bootcamp-korea/10-Likey-backend pull request #7
Opened 2020-08-08 09:02 UTC by Jun4928

## 수정 사항 간략한 한줄 요약
- 장바구니 API 구현 및 테스트 완료
		 
## 수정 사항들 자세한 내용
User 모델의 carts field 에 저장되어있는 배열을 다루는 API

- get: 해당 유저의 carts filed에 저장되어 있는  배열로 return 
- post: body로 담겨오는 actionHandler 값 에 따라 최초로 장바구니에 담는 service 로직과 수량을 조절하는 service 로직으로 세분화
- deleteAll: 해당 유저의 carts filed 에 저장되어 있는 배열 비우기
- deleteOne: 해당 유저의 carts filed 에 저장되어 있는 배열 중 productId 가 일치하는 상품 지우기

## 기타 질문 및 특이 사항
- 레이어링과 모듈화 개선을 한 feature/refactor 브랜치를 pull 받아서 작업 한 브랜치 입니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-08-11 11:14 UTC, joonseokhu requested changes

2020-08-11 11:14 UTC, joonseokhu commented on controllers/cart.js
> +    if (!user) errorHandler("User not found", 404);
로그인한 상태에서만 사용되길 의도하신것 같은데, 미들웨어 흐름제어를 통해 더 깔끔하게 구현 가능합니다.

https://gist.github.com/joonseokhu/ad134d18dd18b136ffe404142b40f823

isAuth에서 토큰에 담긴 id로 user 조회까지 처리하면 해당 유저가 실제로 존재한다는게 증명됩니다.

2020-08-11 11:14 UTC, joonseokhu commented on controllers/product.js
> +    if (!products.length) errorHandler("Products not found", 404);
어떤 엔티티의 목록을 조회하는 api 에서, 해당 목록이 비어있다면, 에러를 띄우면 rest에 어긋납니다.
200으로 돌려주고 빈 배열을 응답하세요.

목록 조회에서의 404를 응답할 상황은 one-many로 조인된 목록을 조회하면서
상위 엔티티(one) 가 없거나, 상위엔티티에 접근할 권한이 없을 때 말고는 없습니다.

2020-08-11 11:14 UTC, joonseokhu commented on controllers/product.js
> +    if (!products.length) errorHandler("Products not found", 404);
어떤 엔티티의 목록을 조회하는 api 에서, 해당 목록이 비어있다면, 에러를 띄우면 rest에 어긋납니다.
200으로 돌려주고 빈 배열을 응답하세요.

목록 조회에서의 404를 응답할 상황은 one-many로 조인된 목록을 조회하면서
상위 엔티티(one) 가 없거나, 상위엔티티에 접근할 권한이 없을 때 말고는 없습니다.

2020-08-11 11:14 UTC, joonseokhu commented on controllers/cart.js
> +    if (!user) errorHandler("User not found", 404);
로그인한 상태에서만 사용되길 의도하신것 같은데, 미들웨어 흐름제어를 통해 더 깔끔하게 구현 가능합니다.

https://gist.github.com/joonseokhu/ad134d18dd18b136ffe404142b40f823

2020-08-11 11:14 UTC, joonseokhu commented on controllers/cart.js
> +      productId: req.params.productId,
삭제된 엔티티의 아이디를 응답하는건 restful 하지 않습니다. 성공여부만 알려줘도 충분합니다.

2020-08-11 11:14 UTC, joonseokhu commented on middleware/isAuth.js
> +    next();
jwt 의 특성상, jwt 에서 꺼낸 값을 그대로 인증정보로 사용하면 안됩니다.

어떤 유저가 회원가입, 로그인 한 후, 생성받은 토큰을 따로 저장해두고
바로 탈퇴한 뒤, 받았던 토큰을 그대로 사용하는 상황을 가정해보세요
api 는 삭제된 유저의 id를 물고 실제 유저가 존재하는것처럼 작동하게 됩니다.

인증처리 미들웨어에서 유저 조회를 한 다음에 결과를 req.user에 넣어두고,
이후 따라오는 미들웨어에선 req.user에 담긴 정보가 신뢰할만하다는 가정하에 작동하도록 만들어주세요

2020-08-11 11:14 UTC, joonseokhu commented on DAO/user.js
> +module.exports = { createOrUpdateUser, findUserById, findUserByEmail };
mongoose 모델이 이미 DTO의 구현체입니다. 서비스로직을 분리하실 의도라면 조금더 고도화된 로직을 만들어주세요

2020-08-11 11:14 UTC, joonseokhu commented on services/cart.js
> +  if (countAction !== "plus" || countAction !== "minus")
enum 타입을 구현하고 싶으신 것 같은데, 어짜피 둘중 하나라면 boolean 타입으로 받으면 어떨까요?

isIncreasing: true -> 늘리기
isIncreasing: false -> 줄이기

2020-08-11 11:14 UTC, joonseokhu commented on models/user.js
> +    type: [Object],
좀더 구체적으로 스키마 만들어주세요.

```js
carts: [{
  product: {
    type: schema.Types.ObjectId,
    ref: 'Product',
  },
  quantity: Number,
}]
```

2020-08-11 11:14 UTC, joonseokhu commented on services/cart.js
> +  });
이렇게 삼항연산자를 쓰면 더 코드가 간결해질 것 같습니다.
```js
foundCartProduct.count + (countAction === "plus" ? +1 : -1)
```

2020-08-11 11:14 UTC, joonseokhu commented on services/cart.js
> +  }
이미 존재하는 상품을 장바구니에 추가할 때, 에러를 내는게 아니라 기존 상품의 수량을 늘리도록 하는게 더 좋지 않을까 싶습니다.

2020-08-11 11:14 UTC, joonseokhu commented on utils/checkPassword.js
> +};
이 모듈을 불러와서 함수를 호출할 바에야, 차라리 이걸 사용할 곳에서 bcrypt를 직접 사용하는게 더 낫지 않을까요?

2020-08-12 02:00 UTC, Jun4928 commented on DAO/user.js
> +module.exports = { createOrUpdateUser, findUserById, findUserByEmail };
수정했습니다!

2020-08-12 02:12 UTC, Jun4928 commented on utils/checkPassword.js
> +};
위의 리뷰 사항 반영해서 다시 올렸습니다!

2020-08-12 02:48 UTC, Jun4928 commented on models/user.js
> +    type: [Object],
저희 의도는 reference를 사용하지 않고, parameter로 들어온 제품을 조회한 다음 quantity 가 포함된 하나의 객체로 재구성해서 저장하려고 했습니다. 레퍼런스를 사용하는게 더 좋은 방법일까요?

2020-08-13 11:01 UTC, merged

2020-08-13 12:36 UTC, joonseokhu commented on models/user.js
> +    type: [Object],
서브컬렉션으로 만들면, 유저가 장바구니에 넣어둔 상품이 단종되는 상황에 대처가 안됩니다.

2020-08-13 12:36 UTC, joonseokhu commented on services/auth.js
> +const dotenv = require("dotenv").config();
? dotenv 계속 이렇게 쓰고 계셨나요?

server.js 최상위에 변수선언없이
```js
require('dotenv').config()
```
이렇게 사용하시고, 나머지 위치에서는 지우세요

node에서 entry point 의 최상위에서 실행되어야 하는 코드입니다.

2020-08-13 12:36 UTC, joonseokhu commented on services/cart.js
> +};
비즈니스 로직의 함수는 인자로 받아온 객체/배열을 변형하면 안됩니다.
인자로 받은 객체인 user의 속성을 바꾸는 식으로 처리하지마세요.
차라리 이 함수를 사용하는 상위 로직에서 나머지를 처리하도록 하고 최대한 순수하게 작성하세요