[Likey: 최준, 오호근] Add: kakao login
wecode-bootcamp-korea/10-Likey-backend pull request #8
Opened 2020-08-08 09:15 UTC by dhgh95

## 수정 사항 간략한 한줄 요약
- signUp 로직 변경
- kakao 소셜 로그인 로직

## 수정 사항들 자세한 내용
- routes / auth.js --> kakao -> signUp -> login 
- controller / auth.js --> signup (소셜회원가입 or 일반회원가입 로직 ), kakao 로그인 로직
- services / auth.js --> createUserData ( user DB에 생성하는 로직), kakaoLoginInfo (access_token으로 카카오톡으로부터 사용자 정보 받아오기)

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-08-11 11:24 UTC, joonseokhu requested changes
카카오 이메일주소와 유저 이메일주소는 별개입니다.

1. 유저 스키마에 `kakaoId` 필드 추가하세요.
2. 카카오로 회원가입시, 새로운 user 생성하면서 카카오에서 주는 uuid 형식이나 bigint 형식의 고유 아이디를 `kakaoId`에 저장하세요.
3. 카카오로 로그인시, 마찬가지로 카카오에서 주는 고유 아이디로 대조해서 로그인 성공여부 결정하고 그 회원의 mongoDB id 로 된 jwt 발급해주세요.
4. 로그인 이후 인증/인가는 jwt 기준으로 하세요

### 즉 로그인 이후엔 이메일로 가입/로그인한 사용자와 카카오로 가입/로그인한 사용자가 구분되지 않아야 합니다.

2020-08-11 11:28 UTC, joonseokhu commented on middleware/is_auth.js
> +  }
토큰이 잘못되거나 만료된 상황은 401 입니다.
500은 서버 내부 에러 입니다.

2020-08-11 11:31 UTC, joonseokhu commented on services/auth.js
> +};
1. axios 의 프로미스 결과값은 컨벤션상 `response` 입니다.
2. 반드시 필요한 상황 아니면 변수 재할당 하지 마세요

```js
() => {
  const { data } = await axios.xxxx()
  return data
}
```

2020-08-12 01:29 UTC, dhgh95 commented on middleware/is_auth.js
> +  }
넵

2020-08-12 01:32 UTC, dhgh95 commented on services/auth.js
> +};
넵 감사합니다

2020-08-13 11:07 UTC, joonseokhu commented
conflict 해결해주세요~

2020-08-13 13:16 UTC, joonseokhu requested changes

2020-08-13 13:16 UTC, joonseokhu commented on routes/auth.js
> +router.post("/kakao", kakao, signUp, login);
카카오 회원가입 처리하는 딱 하나의 라우트 때문에
전용 미들웨어까지 만들고 미들웨어 네개를 붙여두는건 별로입니다.
그냥 비즈니스로직 하나로 통일하세요.

2020-08-13 13:16 UTC, joonseokhu commented on controllers/auth.js
> +    }
if 문 중첩 최대한 줄여야 좋습니다.

**early return** 검색해서 어떤 의미이고 어떻게 작동하는지 공부하신다음 적용하세요

2020-08-13 13:16 UTC, joonseokhu commented on controllers/auth.js
> +    }
카카오/이메일 회원 가입방식이 달라서, 미들웨어 4개를 붙여야 할 정도인데.... 정작 비즈니스로직은 if문 4개씩 써가며 하나의 함수로 처리해야 할까요? 그냥 signUpByEmail / signUpByKakao 두개의 미들웨어 각각 만들어서 붙이면 안되나요?

2020-08-13 13:16 UTC, joonseokhu commented on controllers/auth.js
> +    }
req.kakaoInfo 는 쓰지 마세요. 회원가입/로그인은 전체 어플리케이션에서 극히 일부 도메인에 지나지 않는데, 그것에 따라 어플리케이션의 전역적인 컨텍스트가 변형되어서는 안됩니다.

2020-08-13 13:16 UTC, joonseokhu commented on controllers/auth.js
> +  } catch (err) {
이것도 마찬가지로

1. if 은 early return 하기
2. 하지만 이건 완전히 다르게 작동하는 두 동작을 억지로 합쳤기 때문에 비정상적으로 분기를 많이 하게 되는 것입니다.
3. signup과 마찬가지로 함수 두개로 쪼개세요

하지만 난 꼭! 회원가입과 로그인을 하나의 함수로 처리하고 싶다 하시면
**strategy pattern** 배워서 적용하세요

2020-08-13 13:16 UTC, joonseokhu commented on controllers/auth.js
> +};
이게 클라이언트에서 카카오 authToken 물고 요청을 주는건가요?

일반 authToken이랑 헤더 이름 똑같아서 헷갈립니다.

그리고, 이렇게 처리하면 기 가입된 유저가 (카카오 계정 연결 등을 이유로) 카카오 oauth 처리를 하려고 하면,
원래 발급되었던 토큰을 덮어쓰면서 로그인이 풀립니다.

oauth 를 위한 토큰 처리시
그냥 쿼리스트링으로 으로 토큰 받도록 하세요

2020-08-13 13:16 UTC, joonseokhu commented on controllers/cart.js
> +};
뭔가 잘못된 api 설계같은데

- 장바구니는 지금 별도 모델이 아닙니다. 즉 entity가 아닙니다.
- rest api 서버는 무상태성을 가져야 합니다. entity의 변화에 의해 결과가 달라지는것 말고는 요청에 따라 응답이 왔다갔다 하면 안됩니다.
- 서버는, 클라이언트가 서버대신 뭔가를 저장해주고 기억해줄거라고 기대하면 안됩니다. (인증정보 제외)

지금의 api 설계는, 클라이언트가 현재 유저의 장바구니에 특정 상품이 있는지를 스스로 기억하고 체크할 수 있어야 합니다.
(그래야 countAction 속성을 넣을지말지 고르니깐요 )

하지만, 장바구니를 구현하기 위해 데이터베이스를 사용한다는 의미는,
컴퓨터에서 상품 A, B 를 담고, 곧바로 이어서 핸드폰에서 상품 A, C를 담을 가능성도 염두하겠다는 뜻입니다.

장바구니 속 내용물의 상태를 기억하고 계산하는걸 클라이언트에게 맡기면 안된다는 것입니다
클라이언트는 현재 장바구니에 물건이 들었는지 안들었는지 상관없이 "상품 A를 장바구니에 추가하라"는 요청을 보낼 수 있어야 합니다.

상품A 가 현재 장바구니에 존재하는지, 몇개나 있는지, 장바구니에 상품을 생성해야 하는지, 삭제해야 하는지 갯수를 바꾸어야 하는지는 서버가 알아서 계산해야 합니다.

현재는 장바구니에 없는 상품의 갯수를 추가하려고 하면 에러가 나는 상태같은데
API 디자인 다시하시길 바랍니다.

2020-08-17 06:55 UTC, merged